// Builds TRANSLATR™ into the repository's translatr/ folder (nikstil.com/translatr/), and fills
// BloatOS in with a few facts from the game: its eight themes' cursor sets (os/cursors.css) and the
// numbers on the TRANSLATR™ window (index.html's game-facts).
//
// This folder (translatr-src/) lives inside the nikstil.github.io repository; BloatOS itself
// (index.html, os/) and the shared DOOMSCROLL modules (doomscroll/) are edited in place there.
// Usage: npm run build:site

import { build, createServer } from 'vite'
import { rm, readdir, readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const site = join(root, '..')
const out = join(site, 'translatr')

// The game, with every asset URL prefixed by /translatr/. Old hashed bundles are removed.
await rm(join(out, 'assets'), { recursive: true, force: true })
await build({
  root,
  base: '/translatr/',
  logLevel: 'warn',
  build: { outDir: out, emptyOutDir: false },
})

// nikstil.com online: posts speedruns and Daily Challenges to the leaderboards.
const gamePage = join(out, 'index.html')
const page = await readFile(gamePage, 'utf8')
const bridge = '<script src="/online/translatr-bridge.js" defer></script>'
if (!page.includes(bridge)) await writeFile(gamePage, page.replace('</head>', `    ${bridge}\n  </head>`))

const vite = await createServer({ root, server: { middlewareMode: true }, appType: 'custom', logLevel: 'error', optimizeDeps: { noDiscovery: true } })
const { CURSORS } = await vite.ssrLoadModule('/src/lib/cursors.js')
const { THEMES } = await vite.ssrLoadModule('/src/data/themes.js')
const { ENDINGS } = await vite.ssrLoadModule('/src/data/endings.js')
const { EQUIPPABLE_COUNT } = await vite.ssrLoadModule('/src/data/gameData.js')
const { ACHIEVEMENTS } = await vite.ssrLoadModule('/src/data/achievements.js')
await vite.close()

const cursorCss = THEMES.map((t) => {
  const c = CURSORS[t.cursor]
  return `html[data-theme="${t.id}"] {\n  --cur-arrow: ${c.arrow};\n  --cur-hand: ${c.hand};\n  --cur-lock: ${c.lock};\n}`
}).join('\n')
await writeFile(join(site, 'os', 'cursors.css'), `/* Generated by translatr-src/scripts/build-site.mjs from src/lib/cursors.js. Do not edit. */\n${cursorCss}\n`)

const facts = { endings: ENDINGS.length, items: EQUIPPABLE_COUNT, achievements: ACHIEVEMENTS.length, themes: THEMES.length }
const indexPath = join(site, 'index.html')
const html = await readFile(indexPath, 'utf8')
const withFacts = html.replace(/(<script type="application\/json" id="game-facts">)[^<]*(<\/script>)/, `$1${JSON.stringify(facts)}$2`)
if (withFacts === html && !html.includes(JSON.stringify(facts))) throw new Error('index.html: game-facts script not found')
await writeFile(indexPath, withFacts)

// GitHub Pages runs Jekyll, which silently drops files starting with "_": make sure we have none.
const assets = await readdir(join(out, 'assets'))
const hidden = assets.filter((f) => f.startsWith('_'))
if (hidden.length) throw new Error(`Jekyll would ignore: ${hidden.join(', ')}`)

console.log(`✓ translatr/ built (${assets.length} assets); BloatOS facts ${JSON.stringify(facts)}`)
